sudo: false
language: node_js

matrix:
  include:
    - os: linux
      node_js: "8"
    - os: osx
      node_js: "8"

before_script:
  - npm run lint
  - npm run build

cache:
  yarn: true

notifications:
  email:
    on_success: never
